version: '3.7'

services: 
  db:
    image: mongo:latest
    container_name: 'gateways-mongo-database-server'
    ports: 
      - 27017:27017
    networks:
      - webnet
    volumes:
      - mongodata:/mongo/db  

  api:
    build:
      context: ./gateways
      dockerfile: Dockerfile
      # Could be development | production
      target: development
    volumes:
      - .:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    container_name: 'gateways-nestjs-backend-server'
    links:
      - db
    environment:
      - LISTEN_PORT=3000
      - MONGO_CONNECTION_URI=mongodb://db/musala
      - MAX_DEVICE_PER_GATEWAY=10
    ports:
      - 3000:3000
    command: npm run start
    networks:
      - webnet
    depends_on:
      - db
      
  web:
    build:
      context: ./ng-gateways
      dockerfile: Dockerfile
      # Could be development | production
    volumes:
      - .:/usr/src/app/frontend
      - /usr/src/app/frontend/node_modules
    container_name: 'gateways-angular-frontend-app'
    environment:
      - NGINX_PORT=9000
    ports:
      - 9000:9000
    links:
      - api
    networks:
      - webnet
    depends_on:
      - api
      
networks:
  webnet:
volumes:
  mongodata:
