import {
  IsAlphanumeric,
  IsNotEmpty,
  IsEnum,
  IsNumberString,
} from 'class-validator';

import { DeviceStatus } from '../enums/device-status.enum';
import { Device } from '../schemas/device.schema';

export class DeviceDto {
  constructor(device: Device) {
    if (device) {
      this.id = device.id;
      this.uid = device.uid;
      this.vendor = device.vendor;
      this.createdAt = device.created_at;
      this.status = device.status;
      this.gatewayId = device.gatewayId;
    }
  }

  id!: string;

  @IsAlphanumeric()
  @IsNotEmpty()
  gatewayId: string;

  @IsNumberString()
  @IsNotEmpty()
  uid: string;

  @IsNotEmpty()
  vendor: string;

  @IsEnum(DeviceStatus)
  status: DeviceStatus;

  // Autogenerated
  createdAt: string;
}
